openapi: 3.0.0
info:
  title: Faculty API
  version: 1.0.0
  description: |
    This API manages staff, their offices, and allocated courses within the Faculty of Computing and Informatics.
paths:
  /lecturers:
    get:
      summary: Retrieve a list of all lecturers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
    post:
      summary: Add a new lecturer
      requestBody:
        description: New lecturer data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        '201':
          description: Lecturer added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
  /lecturers/{staffNumber}:
    get:
      summary: Retrieve the details of a specific lecturer by their staff number
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
        '404':
          description: Lecturer not found
    put:
      summary: Update an existing lecturer's information
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Updated lecturer data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        '200':
          description: Lecturer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
        '404':
          description: Lecturer not found
    delete:
      summary: Delete a lecturer's record by their staff number
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Lecturer deleted successfully
        '404':
          description: Lecturer not found
  /courses/{courseCode}/lecturers:
    get:
      summary: Retrieve all the lecturers that teach a certain course
      parameters:
        - name: courseCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
  /offices/{officeNumber}/lecturers:
    get:
      summary: Retrieve all the lecturers that sit in the same office
      parameters:
        - name: officeNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
components:
  schemas:
    Lecturer:
      type: object
      properties:
        staffNumber:
          type: string
        officeNumber:
          type: string
        staffName:
          type: string
        title:
          type: string
        courses:
          type: array
          items:
            type: object
            properties:
              courseName:
                type: string
              courseCode:
                type: string
              nqfLevel:
                type: integer